import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    backgroundColor: '#EBDEDC',
  },
  BackgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    opacity: 0.5,
  },
  title: {
    fontSize: 50,
    fontWeight: 'bold',
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  swapContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  tokenContainer: {
    flex: 2,
    alignItems: 'center',
  },
  tokenLabel: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  input: {
    width: '100%',
    padding: 30,
    borderWidth: 4,
    borderColor: '#ccc',
    borderRadius: 5,
    textAlign: 'center',
  },
  hotValueContainer: {
    width: '100%',
    padding: 30,
    borderWidth: 4,
    borderColor: '#ccc',
    borderRadius: 5,
    textAlign: 'center',
  },
  errorText: {
    color: 'red',
    marginTop: 5,
  },
  tokenValue: {
    fontSize: 40,
    fontWeight: 'bold',
  },
  reviewButton: {
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFEA00',
    paddingVertical: 10,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
    borderColor: '#555',
  },
  reviewButtonText: {
    color: '#111',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  minimumPointsText: {
    color: 'red',
    marginTop: 40,
    padding: 20,
    borderWidth: 5,
    borderColor: '#FFEA00',
    borderRadius: 5,
    textAlign: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
    backgroundColor: 'transparent',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    width: 600,
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
  },
  modalText: {
    fontSize: 18,
    marginBottom: 20,
  },
  closeButton: {
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFEA00',
    paddingVertical: 10,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  closeButtonText: {
    color: 'white',
    fontSize: 16,
  },
  topRightContainer: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  topLeftContainer: { 
    position: 'absolute',
    top: 10,
    left: 10,
  },
  balanceContainer: { 
    alignItems: 'center',
  },
  balanceLabel: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  balanceValue: {
    fontSize: 18,
  },

  topPoint:{       
    backgroundColor: 'transparent',
    padding: 15,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
    width: 180, 
    height: 100, 
  
  },
  topPointbalanceContainer: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  topPointbalance: {
    fontSize: 24,
    fontWeight: 'bold',
  },
});

export default styles;
